-- data exploration
-- dimension exploration
select distinct country from gold.dim_customers;
select distinct category from gold.dim_products;
select distinct category, sub_category, product_name from gold.dim_products
order by 1,2,3 desc;

-- data exploration
-- this helps us understand timespan of our data
select min(order_date) as first_order_date,
max(order_date) as last_order_date,
timestampdiff(month,min(order_date), max(order_date)) as  order_range_month
 from gold.fact_sales;
 
 select 
 min(birthdate),
 timestampdiff(year, min(birthdate), current_date()) as oldest_age,
 max(birthdate),
 timestampdiff(year, max(birthdate), current_date()) as youngest_age
 from gold.dim_customers;
 
 -- Measures exploration
 -- find the total sales
 select sum(sales_amount) as total_sales from gold.fact_sales;
 
 -- find how many items are sold
 select
 sum(quantity) as total_quantity
 from
gold.fact_sales;

-- find average selling price 
 select
 avg(price) as avg_selling_price
 from
gold.fact_sales;

-- total number of orders
select count(distinct order_number) as total_order 
from gold.fact_sales;

-- find total number of products

select count(distinct product_key) as total_products
from gold.dim_products;

-- find total number of customers

select count(customer_key) as total_customers
from gold.dim_customers;

-- find the total number of customer that has placed an order

select count(distinct customer_key) as total_customers 
from gold.fact_sales;

-- Generate a Report that shows all the key metrics of the business

 select 
'total Sales' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union all
 select 'Total Quantity', sum(quantity) from gold.fact_sales
 union all
  select 'Average Price', avg(price) from gold.fact_sales
  union all
  select 'Total no Orders', count(distinct customer_key) from gold.dim_customers
  union all
  select 'Total no Products', count(distinct order_number) from gold.fact_sales
  union all
  select 'Total no customers', count(distinct product_key) from gold.dim_products;
 
 
-- Magnitude Analysis

-- find total customers by countries
select
country,
count(customer_key) as total_customers 
from
gold.dim_customers
group by country
order by total_customers desc;

-- Find total customer by gender
select
gender,
count(customer_key) as total_customers 
from
gold.dim_customers
group by gender
order by total_customers desc;

-- Find total products by category
select
category,
count(product_key) as total_product
from
gold.dim_products
group by category
order by total_product desc;

-- What is the average costs in each category
select
category,
avg(cost) as Average_cost
from
gold.dim_products
group by category
order by Average_cost desc;

-- What is the total revanue generated by each category
select
pr.category,
sum(f.sales_amount) as Total_revenue
from 
gold.fact_sales f
left join gold.dim_products pr
on pr.product_key = f.product_key
group by pr.category
order by Total_revenue desc;

select * from gold.dim_customers
where first_name = 'Jordan'
and last_name = 'Turner';
-- What is the total revenue generated by each customer
select
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as Total_revenue
from 
gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by c.customer_key,c.first_name, c.last_name
order by Total_revenue desc;

-- What is the distribution of sold items aross countries
select
c.country,
sum(f.quantity) as Total_sold_items
from 
gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by c.country
order by Total_sold_items desc;

-- Ranking Analysis

-- Which 5 products generates the highest revenue
select
pr.product_name,
sum(f.sales_amount) as Total_revenue
from 
gold.fact_sales f
left join gold.dim_products pr
on pr.product_key = f.product_key
group by pr.product_name
order by Total_revenue desc
limit 5;

select *
from (
	select
	pr.product_name,
	sum(f.sales_amount) as Total_revenue,
	row_number() over (order by sum(f.sales_amount) desc) as rank_products
	from 
	gold.fact_sales f
	left join gold.dim_products pr
	on pr.product_key = f.product_key
	group by pr.product_name)t
where rank_products <= 5;

-- Which 5 products generates the lowest revenue
select
pr.product_name,
sum(f.sales_amount) as Total_revenue
from 
gold.fact_sales f
left join gold.dim_products pr
on pr.product_key = f.product_key
group by pr.product_name
order by Total_revenue
limit 5;

select *
from (
	select
	pr.product_name,
	sum(f.sales_amount) as Total_revenue,
	row_number() over (order by sum(f.sales_amount)) as rank_products
	from 
	gold.fact_sales f
	left join gold.dim_products pr
	on pr.product_key = f.product_key
	group by pr.product_name)t
where rank_products <= 5;